
##### Checks run at pull request #####
# Check quiz formatting
check-quizzes: yes
# Check that urls in the content are not broken
url-checker: yes
# Spell check Rmds and quizzes
spell-check: yes

##### Renderings run upon merge to main branch #####
# Rendering each platform's content
render-bookdown: yes
render-leanpub: yes
render-coursera: yes

# What docker image should be used for rendering?
# The default is jhudsl/course_template:main
rendering-docker-image: 'jhudsl/course_template:main'
