# Candace Savonen Apr 2021

name: Delete Preview

on:
  pull_request:
    types: [closed]

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          branches: preview-${{ github.event.pull_request.number }}
