
# This code was originally written by Josh Shapiro and Candace Savonen
# for the Childhood Cancer Data Lab, an initiative of Alexs Lemonade Stand Foundation.
# https://github.com/AlexsLemonade/refinebio-examples/blob/33cdeff66d57f9fe8ee4fcb5156aea4ac2dce07f/.github/workflows/style-and-sp-check.yml#L1

# Adapted for this jhudsl repository by Candace Savonen Apr 2021

name: Build, Render, and Push

# Controls when the action will run. Triggers the workflow on push
# events only for the master branch
on:
  push:
    branches: [ main ]
    paths:
      - '**.Rmd'
      - docker/Dockerfile

jobs:
  # This workflow contains a single job called "build-all"
  build-all:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2
        with:
          # get the full repo
          fetch-depth: 0
          # use github PAT
          token: ${{ secrets.GH_PAT }}

###### If you will be making changes to the Docker image to make specific to the
###### course, then highlight this chunk and uncomment it. #####################
###### Recommend using short cut -- Command and / works for some editors.#######
###### START OF DOCKER UPDATE CHUNK
      # # Login to Dockerhub
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      #
      # # Set up Docker build
      # - name: Set up Docker Build
      #   uses: docker/setup-buildx-action@v1
      #
      # - name: Get Token
      #   run: echo ${{ secrets.GH_PAT }} > docker/git_token.txt
      #
      # # Build docker image
      # - name: Build Docker image
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: false
      #     load: true
      #     context: docker
      #     file: docker/Dockerfile
      #     tags: jhudsl/course_template
      #
      # # Push the Docker image
      # - name: Push Docker image
      #   run: docker push jhudsl/course_template

###### END OF DOCKER UPDATE CHUNK ##############################################

      # Run bookdown rendering
      - name: Run bookdown render
        run: |
          docker run \
          --mount type=bind,target=/home/rstudio,source=$PWD \
          jhudsl/course_template \
          Rscript -e "bookdown::render_book('index.Rmd')"

      # Commit the rendered bookdown files
      - name: Commit rendered bookdown files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git add --force docs/*
          git commit -m 'Render bookdown' || echo "No changes to commit"
          git push origin main || echo "No changes to push"

###### If you want automatic Google Slide updates for your course you should
###### uncomment this chunk. ###################################################
###### Recommend using short cut -- Command and / works for some editors.#######
###### START OF GOOGLE SLIDE UPDATE CHUNK
      #
      # # Refresh google slide code images
      # - name: Run google slide refresh script
      #   env:
      #     GOOGLE_SLIDE_ID: ${{ secrets.GOOGLE_SLIDE_ID }}
      #     GOOGLE_SLIDE_ACCESS_TOKEN: ${{ secrets.GOOGLE_SLIDE_ACCESS_TOKEN }}
      #     GOOGLE_SLIDE_REFRESH_TOKEN: ${{ secrets.GOOGLE_SLIDE_REFRESH_TOKEN }}
      #   run: |
      #     docker run \
      #     --mount type=bind,target=/home/rstudio,source=$PWD \
      #     jhudsl/course_template:latest \
      #     Rscript --vanilla scripts/google_slides_image_linker.R \
      #       --slides_id "$GOOGLE_SLIDE_ID" \
      #       --image_loc _bookdown_files \
      #       --image_key_dir resources \
      #       --git_repo ${GITHUB_REPOSITORY} \
      #       --git_branch ${GITHUB_REF#refs/heads/} \
      #       --access_token "$GOOGLE_SLIDE_ACCESS_TOKEN" \
      #       --refresh_token "$GOOGLE_SLIDE_REFRESH_TOKEN"
      #
      # # Refresh google slide code images
      # - name: Download slides
      #   env:
      #     GOOGLE_SLIDE_ID: ${{ secrets.GOOGLE_SLIDE_ID }}
      #     GOOGLE_SLIDE_ACCESS_TOKEN: ${{ secrets.GOOGLE_SLIDE_ACCESS_TOKEN }}
      #     GOOGLE_SLIDE_REFRESH_TOKEN: ${{ secrets.GOOGLE_SLIDE_REFRESH_TOKEN }}
      #   run: |
      #     docker run \
      #     --mount type=bind,target=/home/rstudio,source=$PWD \
      #     jhudsl/course_template:latest \
      #     Rscript --vanilla scripts/google_slide_png_downloader.R \
      #       --slides_id "$GOOGLE_SLIDE_ID" \
      #       --access_token "$GOOGLE_SLIDE_ACCESS_TOKEN" \
      #       --refresh_token "$GOOGLE_SLIDE_REFRESH_TOKEN"
      #
      # # Commit the google slide images just downloaded
      # - name: Commit slide images
      #   run: |
      #     git config --local user.email "actions@github.com"
      #     git config --local user.name "GitHub Actions"
      #     git add -A
      #     git commit -m 'Downloaded Google Slide Images' || echo "No changes to commit"
      #     git push origin main || echo "No changes to push"

###### END OF GOOGLE SLIDE UPDATE CHUNK
