# This code was originally written by Josh Shapiro
# for the Childhood Cancer Data Lab, an initiative of Alexs Lemonade Stand Foundation.
# https://github.com/AlexsLemonade/exercise-notebook-answers

# Adapted for this jhudsl repository by Candace Savonen Apr 2021

name: Copy files from Bookdown to Leanpub repo
# Copy rendered notebooks to Leanpub repo

# This workflow will run when there are changes to docs/ files in THIS repo
on:
  workflow_run:
    workflows: [ "Build, Render, and Push" ]
    branches: [ main ]
    types:
      - completed

jobs:
  file-bookdown-pr:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from Leanpub repo
        uses: actions/checkout@v2
        with:
          repository: jhudsl/ITCR_Documentation_and_Usability_Leanpub
          token: ${{ secrets.GIT_TOKEN }}

      - name: Get docs/ from Bookdown repo
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          sudo apt-get install subversion
          sudo apt install r-base

          # Copy over book.bib file
          svn export --force https://github.com/${GITHUB_REPOSITORY}.git/branches/${GITHUB_REF#refs/heads/}/docs

          # Copy over book.bib file
          svn export --force https://github.com/${GITHUB_REPOSITORY}.git/branches/${GITHUB_REF#refs/heads/}/book.bib

          # Copy over _bookdown.yml
          svn export --force https://github.com/${GITHUB_REPOSITORY}.git/branches/${GITHUB_REF#refs/heads/}/_bookdown.yml

          # Get list of Rmds needing to copy
          Rscript --vanilla scripts/get_rmd_filenames.R

          # Copy over images folder
          svn export --force https://github.com/${GITHUB_REPOSITORY}.git/branches/${GITHUB_REF#refs/heads/}/resources/images resources/images

          # the url from this repo where files will be downloaded from
          base_url=https://${GIT_TOKEN}@raw.githubusercontent.com/${GITHUB_REPOSITORY}/${GITHUB_REF#refs/heads/}

          # remove old Rmd files
          rm $(find . -name '*.Rmd'  | grep '.Rmd' )

          input="resources/rmd_list.txt"
          while IFS= read -r line
          do
            echo "$line"
            curl --fail -s ${base_url}/${line} > ${line}
          done < "$input"

      - name: Create PR with rendered docs files
        uses: peter-evans/create-pull-request@v3
        id: cpr
        with:
          token: ${{ secrets.GIT_TOKEN }}
          commit-message: Copy leanbuild-needed files from Bookdown repository
          signoff: false
          branch: auto_copy_rendered_files
          delete-branch: true
          title: 'GHA: Automated transfer of leanbuild-needed from Bookdown repository'
          body: |
            ### Description:
            This PR auto-generated from github actions which copies the leanbuild-needed files from the from Bookdown repository:
              - All Rmds files listed in the _bookdown.yml file
              - docs/ folder
              - resources/images folder
              - book.bib file
              - _bookdown.yml file

          labels: |
            automated
          reviewers: $GITHUB_ACTOR

      # Write out PR info
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
